### ISSUE TITLE
Svelte support?

### ISSUE THREAD

**Issue by tombroens** [mrspartak/hasura-om#76]
I did a quick test to try the lib in svelte but getting some errors. Does it have svelte support? Seems to be a 'compile' error. Any tips?

Errors:
[Nollup] Listening on http://localhost:5000
preferring built-in module 'events' over local alternative at 'events', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning

ParseError: /node_modules/hasura-om/src/hasura/events.js
Error: ENOENT: no such file or directory, open '/Users/xxxx/Develop/routify/node_modules/hasura-om/src/hasura/events.js'
    at compileModule (/Users/xxx/Develop/routify/node_modules/nollup/lib/impl/NollupCompiler.js:116:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by mrspartak** [comment]
Hi, I don't really have time to test it with svelte, but it should work with any lib cause it has no dependency on any. I use it with VUE and also on the server-side.

**Comment by tombroens** [comment]
Thanks, no problem, maybe the problem is that I want to use it client-side?

**Comment by mrspartak** [comment]
Yes, this could be a reason. Vue uses webpack and it compiles everything fine
